  const styles = {
  
    // ── Featured products ──────────────────────────────
    featured: {
      padding: 'clamp(40px, 6vw, 80px) clamp(16px, 4vw, 40px)',
      background: '#faf8f5',
    },
    productGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
      gap: '28px',
      maxWidth: '1200px',
      margin: '0 auto',
    },
    productCard: {
      background: 'white',
      overflow: 'hidden',
      cursor: 'pointer',
      textDecoration: 'none',
      color: 'inherit',
      display: 'block',
      border: '1px solid #ede8e0',
      transition: 'transform 0.3s, box-shadow 0.3s',
    },
    productImageContainer: {
      position: 'relative',
      height: '300px',
      overflow: 'hidden',
      background: '#f5f1eb',
    },
    productImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      transition: 'transform 0.6s ease',
    },
    productBadge: {
      position: 'absolute',
      top: '16px',
      left: '16px',
      background: '#c0392b',
      color: 'white',
      padding: '4px 10px',
      fontSize: '10px',
      textTransform: 'uppercase',
      letterSpacing: '1px',
      fontFamily: 'sans-serif',
    },
    productInfo: {
      padding: '20px',
      textAlign: 'center',
    },
    productBrand: {
      fontSize: '10px',
      letterSpacing: '2px',
      color: ' var(--dark-coffe)',
      textTransform: 'uppercase',
      fontFamily: 'sans-serif',
      marginBottom: '6px',
    },
    productName: {
      fontSize: '16px',
      fontWeight: '400',
      marginBottom: '8px',
      color: '#1a1a1a',
      letterSpacing: '0.5px',
    },
    productPrice: {
      fontSize: '18px',
      color: ' var(--dark-coffe)',
      fontWeight: '600',
      marginBottom: '14px',
      fontFamily: 'sans-serif',
    },
    productButton: {
      width: '100%',
      padding: '10px 20px',
      background: 'transparent',
      border: '1px solid #1a1a1a',
      color: '#1a1a1a',
      textTransform: 'uppercase',
      letterSpacing: '2px',
      fontSize: '11px',
      cursor: 'pointer',
      fontFamily: 'sans-serif',
      transition: 'all 0.3s',
    },

    // ── Offer banner ───────────────────────────────────
    offerBanner: {
      padding: 'clamp(60px, 8vw, 100px) clamp(20px, 5vw, 40px)',
      background: '#1a1a1a',
      color: 'white',
      textAlign: 'center',
    },
    offerTag: {
      fontSize: '11px',
      letterSpacing: '4px',
      color: ' var(--dark-coffe)',
      textTransform: 'uppercase',
      fontFamily: 'sans-serif',
      marginBottom: '16px',
    },
    offerTitle: {
      fontSize: 'clamp(28px, 5vw, 50px)',
      fontWeight: '300',
      letterSpacing: '4px',
      marginBottom: '16px',
    },
    offerText: {
      fontSize: '15px',
      marginBottom: '28px',
      color: '#aaa',
      lineHeight: '1.7',
      fontFamily: 'sans-serif',
    },
    offerCode: {
      display: 'inline-block',
      padding: '14px 40px',
      border: '1.5px dashed  var(--dark-coffe)',
      color: ' var(--dark-coffe)',
      fontSize: '22px',
      letterSpacing: '5px',
      marginBottom: '30px',
      fontFamily: 'sans-serif',
    },
    offerButton: {
      display: 'inline-block',
      padding: '14px 44px',
      background: ' var(--dark-coffe)',
      color: 'white',
      textDecoration: 'none',
      fontSize: '11px',
      letterSpacing: '3px',
      textTransform: 'uppercase',
      fontFamily: 'sans-serif',
      border: 'none',
      cursor: 'pointer',
    },

    // ── Newsletter ─────────────────────────────────────
    newsletter: {
      padding: 'clamp(50px, 6vw, 80px) clamp(20px, 5vw, 40px)',
      textAlign: 'center',
      background: '#2c3e50',
      color: 'white',
    },
    newsletterTitle: {
      fontSize: 'clamp(20px, 3vw, 28px)',
      fontWeight: '300',
      letterSpacing: '3px',
      marginBottom: '12px',
    },
    newsletterText: {
      fontSize: '14px',
      marginBottom: '28px',
      opacity: 0.75,
      fontFamily: 'sans-serif',
    },
    newsletterForm: {
      display: 'flex',
      maxWidth: '500px',
      margin: '0 auto',
      flexWrap: 'wrap',
      gap: '0',
    },
    newsletterInput: {
      flex: '1 1 200px',
      padding: '14px 18px',
      border: 'none',
      fontSize: '14px',
      background: 'rgba(255,255,255,0.1)',
      color: 'white',
      outline: 'none',
      fontFamily: 'sans-serif',
    },
    newsletterButton: {
      padding: '14px 28px',
      background: 'white',
      color: '#2c3e50',
      border: 'none',
      fontSize: '11px',
      textTransform: 'uppercase',
      letterSpacing: '2px',
      cursor: 'pointer',
      fontWeight: '700',
      fontFamily: 'sans-serif',
    },

    viewAllWrap: {
      textAlign: 'center',
      marginTop: '48px',
    },
    viewAllBtn: {
      display: 'inline-block',
      padding: '13px 44px',
      background: 'transparent',
      border: '1px solid #1a1a1a',
      color: '#1a1a1a',
      fontSize: '11px',
      letterSpacing: '3px',
      textTransform: 'uppercase',
      textDecoration: 'none',
      fontFamily: 'sans-serif',
      cursor: 'pointer',
    },
  };

  export default styles;